# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git zsh-syntax-highlighting zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Local binaries (e.g. rtk, pipx installs)
export PATH="$HOME/.local/bin:$PATH"

# Postgres
export PGHOST=localhost
export PGPORT=5432
export PGUSER=dev

# Aliases
alias gcm='git commit -m'
alias dcu='docker compose up'
alias dcd='docker compose down'

autoload -U add-zsh-hook
autoload -Uz compinit
compinit
